
all:
	cd ./lexical_analyzer/ && $(MAKE)
	cd ./create_tables/ && $(MAKE)
	cd ./lex_list/ && $(MAKE)
	cd ./structs/ && $(MAKE)
	cd ./sym_list/ && $(MAKE)
	cd ./symtable/ && $(MAKE)

clean:
	cd ./lexical_analyzer/ && $(MAKE)	clean
	cd ./create_tables/ && $(MAKE)	clean
	cd ./lex_list/ && $(MAKE)	clean
	cd ./structs/ && $(MAKE)	clean
	cd ./sym_list/ && $(MAKE)	clean
	cd ./symtable/ && $(MAKE)	clean
